version: "3"
services:
    cart_api:
        container_name: cart_api
        build: .
        networks:
            - my_network
        ports:
            - "5002:5002"
        depends_on:
            - redisdata
            
    redisdata:
        image: "redis:alpine"
    
networks:
    my_network:
        driver: bridge